### PR TITLE
[Fix] Crash when running on lower versions of Android

### LINKED ISSUE #11: Crash when running on lower versions of Android
Seems some classes are missing when using the current compile version. Please see details below.
https://stackoverflow.com/questions/45232457/android-studio-notification-channel-cannot-be-imported

```
2021-09-24 11:41:47.410 10073-10073/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.luxoft.sdl_core, PID: 10073
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/NotificationChannel;
        at org.luxoft.sdl_core.SdlLauncherService.enterForeground(SdlLauncherService.java:167)
        at org.luxoft.sdl_core.SdlLauncherService.onStartCommand(SdlLauncherService.java:55)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3522)
        at android.app.ActivityThread.-wrap23(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6623)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.NotificationChannel" on path: DexPathList[[zip file "/data/app/org.luxoft.sdl_core-1/base.apk"],nativeLibraryDirectories=[/data/app/org.luxoft.sdl_core-1/lib/arm64, /data/app/org.luxoft.sdl_core-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.luxoft.sdl_core.SdlLauncherService.enterForeground(SdlLauncherService.java:167) 
        at org.luxoft.sdl_core.SdlLauncherService.onStartCommand(SdlLauncherService.java:55) 
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3522) 
        at android.app.ActivityThread.-wrap23(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6623) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
```

### PR DESCRIPTION
**Pull request by YaroslavLutsenko**
Fix #11 

### Problems
* Starting in Android 8.0 (API level 26), all notifications must be assigned to a channel. 
Lower versions of Android (API level <= 25) don't now anything about notification channel and it was a reason why this crash occurs.
* Starting in Android 9.0 (API level 28) we should start service in foreground and show notification to the user.  

### Changes
* Added version check before service start. For API level >= 28 service will be started in foreground and in background otherwise.  
* Added notifications for API level <= 25 
* Added ability to open MainActivity after click on the notification. Changed UI init state. 

### Testing 
- [x] I have started core on the emulator with API 28 and connected hmi + another emulator (SPT)
- [x] I have started core on the emulator with API 25 and connected hmi + another emulator (SPT)

### CODE REVIEW

File: app/src/main/java/org/luxoft/sdl_core/AndroidTool.java [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+import androidx.annotation.NonNull;
+
+public class AndroidTool {
+
+    /**
+     * Service needs to be foregrounded in Android O and above.
+     * This will prevent apps in the background from crashing when they try to start SdlService,
+     * because Android O doesn't allow background apps to start background services.
+     * */
+    public static void startService(@NonNull Context context, @NonNull Intent intent) {
```
Comment (AKalinich-Luxoft) [inline app/src/main/java/org/luxoft/sdl_core/AndroidTool.java:19]: @YaroslavLutsenko please also provide the description of the incoming params here

File: app/src/main/java/org/luxoft/sdl_core/MainActivity.java [hunk 2]
```diff
@@ -67,8 +68,10 @@ protected void onCreate(Bundle savedInstanceState) {
         start_sdl_button = findViewById(R.id.start_sdl_button);
         stop_sdl_button = findViewById(R.id.stop_sdl_button);
 
-        start_sdl_button.setEnabled(true);
-        stop_sdl_button.setEnabled(false);
+        Intent intent = getIntent();
```
Comment (AKalinich-Luxoft) [inline app/src/main/java/org/luxoft/sdl_core/MainActivity.java]: @YaroslavLutsenko is my understanding correct that tap on notification re-creates the same activity again?
If so, maybe you can have a static private boolean flag to make sure that the activity was already created once and no need to execute the same code again instead of checking `IS_SDL_SERVICE_THREAD_ALIVE` ?
Not sure if we still need to call `setOnClickListener` and the rest of the code again for a new activity

File: app/src/main/java/org/luxoft/sdl_core/SdlLauncherService.java [hunk 3]
```diff
@@ -135,41 +138,79 @@ private void showToastMessage(String message) {
...
             if (channel_id == null) {
                 NotificationChannel channel = new NotificationChannel(APP_ID, SERVICE_NAME, NotificationManager.IMPORTANCE_DEFAULT);
                 notificationManager.createNotificationChannel(channel);
                 channel_id = channel.getId();
             }
 
-            startForeground(FOREGROUND_SERVICE_ID, getServiceNotification("SDL core is starting..."));
+            startForeground(FOREGROUND_SERVICE_ID, getServiceNotification(text));
+        } else {
+            updateServiceNotification(text);
```
Comment (AKalinich-Luxoft) [inline app/src/main/java/org/luxoft/sdl_core/SdlLauncherService.java:197]: @YaroslavLutsenko if older android versions does not have a notification channel, this call probably does nothing. Maybe we can remove it?

File: app/src/main/java/org/luxoft/sdl_core/SdlLauncherService.java [hunk 4]
```diff
@@ -135,41 +138,79 @@ private void showToastMessage(String message) {
...
+    private void exitForeground() {
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
+            stopForeground(true);
+        } else {
+            NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
+            if (notificationManager == null) {
+                Log.w(TAG, "NotificationManager are not available. Notification cannot be canceled.");
+                return;
+            }
+            notificationManager.cancel(FOREGROUND_SERVICE_ID);
```
Comment (AKalinich-Luxoft) [inline app/src/main/java/org/luxoft/sdl_core/SdlLauncherService.java:210]: @YaroslavLutsenko don't we need to cancel the notification for newer Android versions as well?

Comment (YaroslavLutsenko) [reply app/src/main/java/org/luxoft/sdl_core/SdlLauncherService.java:210]: @AKalinich-Luxoft `stopForeground(true);` will remove notification for newer Android versions.

File: app/src/main/java/org/luxoft/sdl_core/SdlLauncherService.java (hunk 3 above)
Comment (YaroslavLutsenko) [reply app/src/main/java/org/luxoft/sdl_core/SdlLauncherService.java:197]: @AKalinich-Luxoft this method will show notification for older android versions as well. `updateServiceNotification(text);` with text "SDL core is starting...". 
I can check version in line 61 - 64 and call `enterForeground()` or `updateServiceNotification(text);` It will allow to delete `updateServiceNotification(text);` from the `enterForeground()`. Will it be better?

File: app/src/main/java/org/luxoft/sdl_core/AndroidTool.java (hunk 1 above)
Comment (YaroslavLutsenko) [reply app/src/main/java/org/luxoft/sdl_core/AndroidTool.java:19]: @AKalinich-Luxoft fixed in (9420db9)

File: app/src/main/java/org/luxoft/sdl_core/MainActivity.java (hunk 2 above)
Comment (YaroslavLutsenko) [reply app/src/main/java/org/luxoft/sdl_core/MainActivity.java]: @AKalinich-Luxoft I have found another way: add PendingIntent.FLAG_IMMUTABLE to the PendingIntent. 
In future we can change launchMode of MainActivity to prevent similar problems

**Review by VadymLuchko — APPROVED** [review]

File: app/src/main/java/org/luxoft/sdl_core/SdlLauncherService.java (hunk 3 above)
Comment (AKalinich-Luxoft) [reply app/src/main/java/org/luxoft/sdl_core/SdlLauncherService.java:197]: @YaroslavLutsenko my question was just about `updateServiceNotification` in this `else` branch.
I am okay with the existing solution

**Review by AKalinich-Luxoft — APPROVED** [review]

**Review by ychernysheva — APPROVED** [review]
